language: node.js
node_js:
    - 13

services:
    - docker

# pre-testing installs
install:
    - echo "nothing needs to be installed"

# scripts to be run such as tests
before_script:
    - echo "no test"

script:
    # print the version for logging
    - docker --version
    - docker build -t simple-node .
    - docker tag simple-node dinhdangkhoa0201/simple-node:latest

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push dinhdangkhoa0201/simple-node
